version: "3.8"

services:
  database:
    image: database
    container_name: database
    build:
      context: ./postgres
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./postgres/.env
    volumes:
      - postgres-db:/var/lib/postgresql/data
    expose:
      - 5432

  backend:
    image: backend
    container_name: backend
    build:
      context: ./back
      dockerfile: Dockerfile
    env_file:
      - ./back/.env

  frontend:
    image: frontend
    container_name: frontend
    build:
      context: ./front
      dockerfile: Dockerfile
    env_file:
      - ./front/.env.production

  nginx-proxy:
    image: nginx-proxy
    container_name: nginx-proxy
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 3001:3001

volumes:
  postgres-db:
