version: "3.8"

services:
  database:
    image: postgres:alpine
    container_name: database
    restart: always
    env_file:
      - ./postgres/.env
    ports:
      - 5432:5432
    volumes:
      - ./postgres/persist:/var/lib/postgresql
