version: "3.8"

services:
  database:
    image: postgres:alpine
    container_name: database
    restart: always
    env_file:
      - ./postgres/.env
    ports:
      - 5432:5432
    volumes:
      - ./postgres/db:/var/lib/postgresql/data

  backend:
    image: backend
    container_name: backend
    build:
      context: ./back
      dockerfile: Dockerfile
    env_file:
      - ./back/.env
    ports:
      - 3001:3001
